#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TMDB.GrossReports;

namespace TMDB.GrossReports	
{
	public partial class GrossReports : OpenAccessContext, IGrossReportsUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public GrossReports()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public GrossReports(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public GrossReports(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public GrossReports(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public GrossReports(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Grossreport> Grossreports 
		{
			get
			{
				return this.GetAll<Grossreport>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
		
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of GrossReports.
		/// </summary>
		/// <param name="config">The BackendConfiguration of GrossReports.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IGrossReportsUnitOfWork : IUnitOfWork
	{
		IQueryable<Grossreport> Grossreports
		{
			get;
		}
	}
}
#pragma warning restore 1591
